### PR TITLE
Add javascript support

### PR DESCRIPTION
**Pull request by DonnieWest**
By setting `let g:tsuquyomi_javascript_support = 1` it will enable javascript support

### CODE REVIEW

**Comment by DonnieWest** [comment]
This enables support for tsserver based completions with Javascript files. It's something I was fiddling around with locally, so feel free to take it or leave it. The biggest thing that doesn't work at the moment is the import functionality and I'm not sure of how to implement that while maintaining typescript functionality

This file could be more DRY, but currently this allows for removing things easily that may or may not work

**Comment by Quramy** [comment]
Thank you for your PR :)

I got the following error:

```
Error detected while processing tsuquyomi/ftplugin/javascript.vim:
line    8:
E121: Undefined variable: g:tsuquyomi_javascript_support
E15: Invalid expression: !g:tsuquyomi_javascript_support
```

You should check whether  `g:tsuquyomi_javascript_support` exists. Please see https://github.com/Quramy/tsuquyomi/blob/master/plugin/tsuquyomi.vim#L22 .

**Comment by DonnieWest** [comment]
@Quramy I think that fixes it, but I can verify a bit later :)

**Comment by DonnieWest** [comment]
@Quramy yep, that seems to have fixed the issue :+1: 

Thanks for the feedback

**Pull request merged**
